# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Professional Photography, Videography &amp; Design Services | Wisconsin
email: hello@secondcropcreative.com
description: > # this means to ignore newlines until "baseurl:"
  Specializing in photography, videography & web design our goal is to show your story & emotionally connect with your audience. Connect with us today.
twitter:
  username: 2cropcreative
  social:
  name: Second Crop Creative
  links:
    - https://twitter.com/2cropcreative
    - https://www.facebook.com/secondcropcreative
    - https://www.instagram.com/secondcropcreative
    - https://pinterest.com/secondcrop
    - https://www.youtube.com/c/Secondcropcreativedesign/
    - https://vimeo.com/secondcropcreative
github_username:  12oss

# Build settings
markdown:         kramdown
theme:            minima


#Teaser Image
image:
  teaser: 
  feature: 

#Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Permalinks
# HELPFUL
#https://mmistakes.github.io/minimal-mistakes/docs/configuration/
#http://coopcoding.com/blog/my-jekyll-setup-for-this-blog/
permalink: /:categories/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      category: "blog"

#html compress
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             12055
baseurl:          ""
#Production : https://12oss.github.io/secondcropcreative/
#DEV : http://0.0.0.0:12055/secondcropcreative/
#site.github.url
#site.baseurl
url:              "http://secondcropcreative.com"
encoding:         UTF-8


# Disqus post comments
disqus_shortname: SecondCropCreative


#Compress HTML
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []


# Gems
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  #- github-pages
  #- jekyll-github-metadata

